services:
  db:
    image: postgres:15
    container_name: url-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      target: dev
    env_file:
      - .env
    container_name: url-backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    working_dir: /app
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: npm run start:dev

  frontend:
    build:
      context: ./frontend
      target: dev
    env_file:
      - .env
    container_name: url-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  pgdata:
