services:
  db:
    image: postgres:15
    container_name: url-db
    environment:
      POSTGRES_DB: shortener
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      target: prod
    container_name: url-backend
    environment:
      - DATABASE_URL=postgres://user:pass@db:5432/shortener
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      target: prod
    container_name: url-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  pgdata:
