services:
  db:
    image: postgres:15
    container_name: url-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      target: prod
    env_file:
      - .env
    container_name: url-backend
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      target: prod
    env_file:
      - .env
    container_name: url-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  pgdata:
